### PR TITLE
Feature/use config for all urls

### PR DESCRIPTION
**Pull request by fivejjs**
add urls into configure yaml

### CODE REVIEW

**Comment by cbur24** [comment]
@Kirill888 Not looking for you provide a review of the changes in this PR specifically, but rather hoping you can go over some of the code in our repo to identify any improvements we can/should make to our `odc-stats` plugin workflow.

The files that I think you could provide some insight on are:
- The plugin, located here: [gm_ml_pred.py](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/dea_ml/dea_ml/plugins/gm_ml_pred.py)
- The functions that are run by the plugin: [feature_layer.gm_mads_two_seasons_prediction](https://github.com/digitalearthafrica/crop-mask/blob/1b86a58a26cdb9311d1861b4650ab48581142ec1/production/dea_ml/dea_ml/core/feature_layer.py#L135), and [post_processing.py](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/dea_ml/dea_ml/core/post_processing.py)
- Our copy of the [run script](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/dea_ml/dea_ml/pipeline/pred_run.py) 

The config files, [ml_config.yaml](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/dea_ml/dea_ml/config/ml_config.yaml) and [plugin_product.yaml](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/dea_ml/dea_ml/config/plugin_product.yaml) are how we control some of the inputs to the plugin/odc-stats.

If you'd like to run the workflow the notebook [here](https://github.com/digitalearthafrica/crop-mask/blob/feature/use-config-for-all-urls/production/1_test_plugin.ipynb) should just work as long as you install the packages at the top (only in the `capetown-dev` sandbox)

**Comment by Kirill888** [comment]
Looks like you are not using Dask for this, like you do all the work inside `.input_data` and then some more work in `.reduce`. So it won't work with our processing pipelines as it will block until computation is finished inside of the `.input_data` and then some more in `.reduce`

**Comment by Kirill888** [comment]
You need to make sure that both `.input_data` and `.reduce` return quickly and only construct Dask graph, without actually executing any data load/processing operations inline.

**Comment by cbur24** [comment]
Thanks @Kirill888. The `input_data` side should be returning a dask graph, but on the `reduce` side you're right, some of the steps involve computations. We can try now to wrap the image segmentation parts with dask.delayed.

I don't really understand though what you mean by "it won't work with our processing pipelines", as we tested this both in Kubernetes and the Sandbox and we get the results we expect. Is it something to do with the orchestration of many pods running simultaneously (the step we haven't tested)?

**Comment by Kirill888** [comment]
yes, when you have multiple workers, you'll end up with several of them processing same tile, because it will get an SQS message which times out after several minutes and needs to be renewed, renewal won't be happening, as we only renew while task is running on the Dask worker, and not while it is being "prepared to run", but since you are running it instead of just preparing it, it won't work. Also you won't get parallel saving of image files, cause you'll be giving real pixel no Dask pixels, and will just save one image at a time I assume

**Comment by cbur24** [comment]
Ok I think that makes sense to me now. @fivejjs sounds like we need to wrap the image segmentation code with `dask.delayed` to prevent it running during the "preparation" stage, and we need to make sure the `feature_layer.gm_mads_two_seasons_prediction` function isn't actually loading the external datasets. I can begin work on the latter if you start working on the former.  I suggest we merge this PR and start a new branch to add these features.

**Pull request merged**
