### PR TITLE
Feature/k8s image pipeline tunning

### PR DESCRIPTION
**Pull request by fivejjs**
raised again for the update review

### CODE REVIEW

**Comment by cbur24** [comment]
This file `production/dea_ml/dea_ml/core/feature_layer.py` is not how I want it.
- you still have the old `merge_tids_into_ds` in this file, we don't need this function anymore.
- Use the feature layer functions [here](https://github.com/digitalearthafrica/crop-mask/blob/feature/k8s-image-pipeline-tunning/production/feature_layer_functions.py), rather than unnecessarily re-writing different version of the same functionality, as well as duplicating functions that are in `deafrica-tools`. We want to minimize the complexity of the transition from testing to production. I accept there may have to be some edits to the testing functions before they can be used in production but they should be as similar as possible.

The DockerFile is probably still too unwieldy but as long as it works I don't mind.  @alexgleith can help us pare back the unnecessary functionality, as there are a lot of libraries that I'm not familiar with.

**Comment by alexgleith** [comment]
I can't review this.

Can we please separate the Docker components into their own PR?

**Comment by cbur24** [comment]
Agreed with @alexgleith, there are too many files in this PR. Se parting the code from the Docker stuff will make it easier to parse

**Comment by fivejjs** [comment]
split the docker and code in one pr

**Pull request closed without merging**
